# Ex-7-3-One-Hot-Encoder

In [2]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore')


In [10]:
data = [ ['cat', 1], ['cat', 2], ['dog', 3], ['cat', 2], ['fish', 0] ]
enc.fit_transform(data)
enc.categories_

[array(['cat', 'dog', 'fish'], dtype=object),
 array([0, 1, 2, 3], dtype=object)]

In [11]:
X1 = enc.transform([['cat', 1]]).toarray()
print(X1)

[[1. 0. 0. 0. 1. 0. 0.]]


In [12]:
X1 = enc.transform([['dog', 3]]).toarray()
print(X1)

[[0. 1. 0. 0. 0. 0. 1.]]


In [13]:
X = enc.transform(data).toarray()
print(X)

[[1. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 1. 0. 0. 0.]]


In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [15]:
df = pd.DataFrame(data)

In [16]:
df.head()

0  1
0   cat  1
1   cat  2
2   dog  3
3   cat  2
4  fish  0

In [17]:
X=pd.get_dummies(df)
X

1  0_cat  0_dog  0_fish
0  1      1      0       0
1  2      1      0       0
2  3      0      1       0
3  2      1      0       0
4  0      0      0       1